#ifndef QTPLUGINEXAMPLE_GLOBAL_H
#define QTPLUGINEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTPLUGINEXAMPLE_LIBRARY)
#define QTPLUGINEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define QTPLUGINEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // QTPLUGINEXAMPLE_GLOBAL_H
